# Murano Product Spec File - Smart Lighbulb Example Application

resources:
-   alias: temperature
    format: number
-   alias: humidity
    format: number
-   alias: state
    format: number
    initial: 0
-   alias: uptime
    format: number
